Release 2.3.1:
Updated upload script to handle bz2.

diff --git a/upload b/upload
--- a/upload
+++ b/upload
@@ -2,22 +2,32 @@
 
 if [ -n "$1" ] ; then
 	if echo $1 | grep -qv roxterm ; then
-		f=roxterm-${1}.tar.gz
+	    s=bz2
+		f=roxterm-${1}.tar.bz2
+		if [ ! -f "$f" ] ; then
+            f=roxterm-${1}.tar.gz
+        fi
 	else
 	    f="$1"
+	    s=gz
 	fi
 else
-	f=roxterm-*.tar.gz
+	f=roxterm-*.tar.bz2
+	s=bz2
 	if echo $f | egrep -q ' |\*' ; then
-		echo >&2 "Can't work out what version you want to upload"
-		exit 1
-	fi
+        f=roxterm-*.tar.gz
+        if echo $f | egrep -q ' |\*' ; then
+            echo >&2 "Can't work out what version you want to upload"
+            exit 1
+        fi
+        s=gz
+    fi
 fi
 
-d=`echo $f | sed 's/roxterm-//;s/.tar.gz//'`
+d=`echo $f | sed "s/roxterm-//;s/.tar.$s//"`
 mkdir $d
 cp $f $d
 
-rsync -avP -e ssh $d realh,roxterm@frs.sourceforge.net:/home/frs/project/r/ro/roxterm/roxterm/
+#rsync -avP -e ssh $d realh,roxterm@frs.sourceforge.net:/home/frs/project/r/ro/roxterm/roxterm/
 
-rm -rf $d
+#rm -rf $d
