Simplified upload script.

diff --git a/upload b/upload
--- a/upload
+++ b/upload
@@ -1,34 +1,11 @@
 #!/bin/sh
 
-if [ -n "$1" ] ; then
-    s=bz2
-    f=build/roxterm-${1}.tar.bz2
-    if [ ! -f "$f" ] ; then
-        f=roxterm-${1}.tar.gz
-        s=gz
-        if [ ! -f "$f" ] ; then
-            echo >&2 "Can't find a tarball for $1"
-            exit 1
-        fi
-    fi
-else
-	f=build/roxterm-*.tar.bz2
-	s=bz2
-	if echo $f | egrep -q ' |\*' ; then
-        f=roxterm-*.tar.gz
-        if echo $f | egrep -q ' |\*' ; then
-            echo >&2 "Can't work out what version you want to upload"
-            exit 1
-        fi
-        s=gz
-    fi
+f=$1
+if [ ! -f $f ] ; then
+    echo "File not found or given" >&2
+    exit 1
 fi
-
-if [ $s = "bz2" ] ; then
-    d=`echo $f | sed 's|build/roxterm-||;s/.tar.bz2//'`
-else
-    d=`echo $f | sed 's/roxterm-//;s/.tar.gz//'`
-fi
+d=`basename $f | sed 's/roxterm-//;s/.tar.bz2//'`
 mkdir $d
 cp $f $d
 
